# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.cache/wt [current_project]
set_property parent.project_path E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/PC.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/signZeroExtend.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/registerFile.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/mux.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/instructionMemory.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/dataMemory.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/controlUnit.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/ALU.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/counter.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/clock_div.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/key.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/change.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/SegLED.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/singleCircleCPU.v
  E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/sources_1/new/basys3.v
}
read_xdc E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/constrs_1/new/singleCircleCPU.xdc
set_property used_in_implementation false [get_files E:/Xlink/VivadoProject/singleCircleCPU/singleCircleCPU.srcs/constrs_1/new/singleCircleCPU.xdc]

synth_design -top basys3 -part xc7a35tcpg236-1
write_checkpoint -noxdef basys3.dcp
catch { report_utilization -file basys3_utilization_synth.rpt -pb basys3_utilization_synth.pb }
